### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by XJX-187** [andrewsonga/Total-Recon#9]
Hello, I encountered an issue during training where I couldn't find the corresponding file. How can I solve this problem.After downloading and deploying the project again, I still encountered an error.
`FileNotFoundError: [Errno 2] No such file or directory: 'logdir//humandog-stereo000-animal-leftcam-e120-b256-ft2/params_latest.pth'`

**Comment by andrewsonga** [comment]
Hello,

Could you perhaps provide the full error message?
Exactly which script was raising this error?

That would greatly help me help you debug this.

Best,
Andrew.

**Comment by XJX-187** [comment]
Sorry, the previous output log has disappeared. We are currently trying to run the third step "(3) Preprocess raw data" again, and the following issues have occurred：
`database/DAVIS/Pixels/Full-Resolution//humandog-stereo000-animal-leftcam/32_00288
error loading densepose surface
error loading densepose feature
warning: loading empty camera
database/DAVIS/Cameras/Full-Resolution/humandog-stereo000-animal-leftcam/00320.txt
error loading densepose surface
error loading densepose feature
warning: loading empty camera
database/DAVIS/Cameras/Full-Resolution/humandog-stereo000-animal-leftcam/00352.txt
database/DAVIS/Pixels/Full-Resolution//humandog-stereo000-animal-leftcam/32_00320
error loading densepose surface
error loading densepose feature
warning: loading empty camera
database/DAVIS/Cameras/Full-Resolution/humandog-stereo000-animal-leftcam/00352.txt
error loading densepose surface
error loading densepose feature
warning: loading empty camera
database/DAVIS/Cameras/Full-Resolution/humandog-stereo000-animal-leftcam/00384.txt
database/DAVIS/Pixels/Full-Resolution//humandog-stereo000-animal-leftcam/32_00352
/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: /usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
# workers: 2
# pairs: 2
init:0, end:-1
trying per-image loader
inside VidDataset
SELF.CROP_FACTOR = 1.0
inside VidDataset
failed per-image loader
Traceback (most recent call last):
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 135, in <module>
    app.run(main)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 67, in main
    data_info = trainer.init_dataset()
  File "/home/mnt/Total-Recon/./nnutils/train_utils_obj.py", line 136, in init_dataset
    self.dataloader = frameloader_obj.data_loader(opts_dict)
  File "/home/mnt/Total-Recon/./dataloader/frameloader_obj.py", line 38, in data_loader
    data_inuse = config_to_dataloader(opts_dict)
  File "/home/mnt/Total-Recon/./utils/io_obj.py", line 352, in config_to_dataloader
    dataset = torch.utils.data.ConcatDataset(datalist)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __init__
    assert len(self.datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable
/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: /usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
# workers: 2
# pairs: 2
init:0, end:-1
trying per-image loader
inside VidDataset
SELF.CROP_FACTOR = 1.0
inside VidDataset
failed per-image loader
Traceback (most recent call last):
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 135, in <module>
    app.run(main)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 67, in main
    data_info = trainer.init_dataset()
  File "/home/mnt/Total-Recon/./nnutils/train_utils_obj.py", line 136, in init_dataset
    self.dataloader = frameloader_obj.data_loader(opts_dict)
  File "/home/mnt/Total-Recon/./dataloader/frameloader_obj.py", line 38, in data_loader
    data_inuse = config_to_dataloader(opts_dict)
  File "/home/mnt/Total-Recon/./utils/io_obj.py", line 352, in config_to_dataloader
    dataset = torch.utils.data.ConcatDataset(datalist)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __init__
    assert len(self.datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable
/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: /usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
# workers: 2
# pairs: 2
init:0, end:-1
trying per-image loader
inside VidDataset
SELF.CROP_FACTOR = 1.0
inside VidDataset
failed per-image loader
Traceback (most recent call last):
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 135, in <module>
    app.run(main)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mnt/Total-Recon/preprocess/img2lines.py", line 67, in main
    data_info = trainer.init_dataset()
  File "/home/mnt/Total-Recon/./nnutils/train_utils_obj.py", line 136, in init_dataset
    self.dataloader = frameloader_obj.data_loader(opts_dict)
  File "/home/mnt/Total-Recon/./dataloader/frameloader_obj.py", line 38, in data_loader
    data_inuse = config_to_dataloader(opts_dict)
  File "/home/mnt/Total-Recon/./utils/io_obj.py", line 352, in config_to_dataloader
    dataset = torch.utils.data.ConcatDataset(datalist)
  File "/usr/local/lib/miniconda3/envs/totalrecon-cu113/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __init__
    assert len(self.datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable`
